[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "YOUR_BACKEND_URL_HERE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]

    Cache-Control = "public, max-age=31536000, immutable"
